### ISSUE TITLE
FormattedValues not being returned from query expression with selected columnset

### ISSUE THREAD

**Issue by bl-pr** [jordimontana82/fake-xrm-easy#307] opened 2018-05-08 07:14 UTC
Where a query expression contains selected list of attributes in the columnset, the injected formattedvalue is not returned.

**Comment by jordimontana82** [comment] 2018-05-09 20:27
Could you please post a unit test to reproduce this?

**Comment by bl-pr** [comment] 2018-05-09 23:12
@jordimontana82  - unit test as requested...

            var context = new XrmFakedContext();
            var service = context.GetFakedOrganizationService();

            var account = new Account() { Id = Guid.NewGuid() };
            account["statecode"] = new OptionSetValue(0);

            var formattedValues = new FormattedValueCollection();
            formattedValues.Add("statecode", "Active");
            account.Inject("FormattedValues", formattedValues);

            context.Initialize(new List<Entity>()
            {
                account
            });

            var a = service.Retrieve("account", account.Id, new ColumnSet("statecode"));
            Assert.True(a.FormattedValues != null);
            Assert.True(a.FormattedValues.Contains("statecode"));
            Assert.Equal("Active", a.FormattedValues["statecode"]);

**Comment by siddharthgupta255** [comment] 2018-06-04 05:34
Hi Team,  

Any updates on this or any workarounds?

Thanks :)

**Comment by mivra** [comment] 2018-06-08 16:33
It's an issue for us too :(

**Comment by jordimontana82** [comment] 2018-06-11 07:57
I think this might happen because attribute projection doesn't use the .Clone method (which also clones formattedvalues) but it creates a brand new instance with the projected (selected) attributes in the column set.

Clone method:
https://github.com/jordimontana82/fake-xrm-easy/blob/eda314d414cbfc8ad8302fe215f3670f87da6132/FakeXrmEasy.Shared/Extensions/EntityExtensions.cs#L246-L253

I think it could be fixed in here: 

https://github.com/jordimontana82/fake-xrm-easy/blob/eda314d414cbfc8ad8302fe215f3670f87da6132/FakeXrmEasy.Shared/Extensions/EntityExtensions.cs#L71-L99 

by copying FormattedValues across as part of the CloneAttributes method, similarly to what the .Clone method above does, where 'e' is the original entity, which should contain formatted values, nad 'projected' is the resulting projected entity.


Any volunteers for a PR?

**Comment by jordimontana82** [comment] 2018-08-09 23:25
This was resolved in #329 and released in v1.46.1

**Closed by jordimontana82** 2018-08-09 23:25 UTC
Labels: bug
