### ISSUE TITLE
FetchXml Link-type='outer'

### ISSUE THREAD

**Issue by mikeread2018** [jordimontana82/fake-xrm-easy#312] opened 2018-05-23 08:47 UTC
Hi - when using fetch and 2 or more linked entities, if the second linked entity (in this case the same physical entity) uses an outer join - no records are returned:

Test to reproduce

`using Crm;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using System;
using Xunit;

namespace FakeXrmEasy.Tests.Issues
{
    public class IssueReady2Code
    {
        [Fact]
        public void Reproduce_issue_Ready2Code()
        {
            var context = new XrmFakedContext();
            var fakedService = context.GetOrganizationService();

            var accountId = Guid.NewGuid();

            Account account = new Account();
            account.Id = accountId;
            account.Name = "Test Account";

            Contact contact = new Contact();
            contact.FirstName = "Dave";
            contact.LastName = "Contact";
            contact.ParentCustomerId = new EntityReference("account", accountId);
            contact.JobTitle = "Developer";

            Contact contact2 = new Contact();
            contact2.FirstName = "Simon";
            contact2.LastName = "Contact";
            contact2.ParentCustomerId = new EntityReference("account", accountId);
            contact2.JobTitle = "Tester2";

            fakedService.Create(account);
            fakedService.Create(contact);
            fakedService.Create(contact2);

            string fetchXml = $@"
            <fetch distinct='true' no-lock='true' >
                <entity name='account' >
                    <attribute name='name' />
                    <filter>
                        <condition attribute='accountid' operator='eq' value='{accountId}' />
                    </filter>
                    <link-entity name='contact' from='parentcustomerid' to='accountid' alias='dev' >
                        <attribute name='firstname' />
                        <filter>
                            <condition attribute='jobtitle' operator='eq' value='Developer' />
                        </filter>
                    </link-entity>
                    <link-entity name='contact' from='parentcustomerid' to='accountid' link-type='outer' alias='tester' >
                        <attribute name='firstname' />
                        <filter>
                            <condition attribute='jobtitle' operator='eq' value='Tester' />
                        </filter>
                    </link-entity>
                </entity>
            </fetch>";

            EntityCollection result = fakedService.RetrieveMultiple(new FetchExpression(fetchXml));
            Assert.Equal(1, result.Entities.Count);

        }

    }
}
`

**Comment by jordimontana82** [comment] 2018-05-24 09:20
Thx for raising this Mike.

Looks like this is a duplicate of #256

**Closed** 2018-07-19 23:32 UTC
Labels: bug
