### ISSUE TITLE
Error: {"When using arithmetic values in Fetch a ProxyTypesAssembly must be used in order to know which types to cast values to."}

### ISSUE THREAD

**Issue by siddharthgupta255** [jordimontana82/fake-xrm-easy#302] opened 2018-04-18 18:04 UTC
Hi,

I am trying to write a unit test case for a plugin which is fetching active records . However, I am getting this error, **{"When using arithmetic values in Fetch a ProxyTypesAssembly must be used in order to know which types to cast values to."}** when I run my unit test.

Pls refer to the code below

Unit Test Code-
`[TestMethod]
        public void TestMethodWithFakedContext()
        {
            XrmFakedContext context = new XrmFakedContext();

            var sEntityLogicalName = "opportunity";
            var gEntityGuid = Guid.NewGuid();

            #region Define Entities & Values

            Entity eTargetEntity = new Entity(sEntityLogicalName);
            eTargetEntity.Id = gEntityGuid;
            eTargetEntity["new_approvalstatus"] = new OptionSetValue(865580010);

            Entity approvalEntity1 = new Entity("new_approval");
            approvalEntity1.Id = Guid.NewGuid();
            approvalEntity1["activityid"] = approvalEntity1.Id;
            approvalEntity1["subject"] = "Approval 1";
            approvalEntity1["regardingobjectid"] = new EntityReference(sEntityLogicalName, gEntityGuid);
            approvalEntity1["statecode"] = new OptionSetValue(0); // Open
            approvalEntity1["statuscode"] = new OptionSetValue(865580000);    // Not Started

            Entity approvalEntity2 = new Entity("new_approval");
            approvalEntity2.Id = Guid.NewGuid();
            approvalEntity2["activityid"] = approvalEntity2.Id;
            approvalEntity2["subject"] = "Approval 2";
            approvalEntity2["regardingobjectid"] = new EntityReference(sEntityLogicalName, gEntityGuid);
            approvalEntity2["statecode"] = new OptionSetValue(0);             // Open
            approvalEntity2["statuscode"] = new OptionSetValue(865580001);    // Pending

            Entity approvalEntity3 = new Entity("new_approval");
            approvalEntity3.Id = Guid.NewGuid();
            approvalEntity3["activityid"] = approvalEntity3.Id;
            approvalEntity3["subject"] = "Approval 3";
            approvalEntity3["regardingobjectid"] = new EntityReference(sEntityLogicalName, gEntityGuid);
            approvalEntity3["statecode"] = new OptionSetValue(0);             // Open
            approvalEntity3["statuscode"] = new OptionSetValue(865580001);    // Pending

            List<Entity> entityList = new List<Entity>();
            entityList.Add(eTargetEntity);
            entityList.Add(approvalEntity1);
            entityList.Add(approvalEntity2);
            entityList.Add(approvalEntity3);

            #endregion
            
            // Initializing all the entities in FAKE context
            context.Initialize(entityList);

            // Define Input Parameter for FAKE context
            ParameterCollection inputParameters = new ParameterCollection();
            inputParameters.Add("sRecordEntityName", sEntityLogicalName);
            inputParameters.Add("sRecordGuid", gEntityGuid.ToString());

            context.ExecutePluginWith<RecallApproval>(inputParameters, null, null, null);
     
        }`

`   
                  ITracingService tracingService =
                (ITracingService)serviceProvider.GetService(typeof(ITracingService));
            IPluginExecutionContext context =
                (IPluginExecutionContext)serviceProvider.GetService(typeof(IPluginExecutionContext));

            IOrganizationServiceFactory serviceFactory =
                (IOrganizationServiceFactory)serviceProvider.GetService(typeof(IOrganizationServiceFactory));

            IOrganizationService service = serviceFactory.CreateOrganizationService(context.UserId);

            // The code which every Plugin needs to have at the beginning ends here

            #endregion
            
            if (context.InputParameters.Contains("sRecordEntityName") && context.InputParameters.Contains("sRecordGuid"))
            {
                var sEntityLogicalName = (context.InputParameters["sRecordEntityName"].ToString());
                var sEntityGuid = (context.InputParameters["sRecordGuid"].ToString());
                sEntityGuid = sEntityGuid.Replace("-", ""); // remove "-" from GUID
                Guid gEntityGuid = Guid.Parse(sEntityGuid);

                Entity eTargetEntity = service.Retrieve(sEntityLogicalName, gEntityGuid, new ColumnSet(new string[] { "new_approvalstatus" }));
                
                try
                {   // Change Entity Logical name as per DEV Environment Approval Entity --> new_approval
                    Entity approvalEntity = new Entity("new_approval");
                    
                    var iSetStateCode = 1;          // StateCode for Completed in Approval
                    var iSetStatusCode = 865580004; // StatusCode for Recalled in Approval
                    var iSetApprovalStatus = 865580040; // OptionSet Value for Recalled in Main Target Record
                    var iRetrieveValueCount = 0;
                    
                    var gRegardingGuid = eTargetEntity.Id; // target Guid to be Set into Regarding Guid
                    
                    #region FetchXML Data Retrieve
                    
                    // This will give all the OPEN Approval process with 

                    string sApprovalRecord = string.Empty;
                    sApprovalRecord = "<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'>";
                    sApprovalRecord += "<entity name='new_approval'>";
                    sApprovalRecord += "<attribute name='activityid' />";
                    sApprovalRecord += "<attribute name='subject' />";
                    sApprovalRecord += "<attribute name='regardingobjectid' />";
                    sApprovalRecord += "<order attribute='subject' descending='false' />";
                    sApprovalRecord += "<filter type='and'>";
                    sApprovalRecord += "<condition attribute='statecode' operator='eq' value='0' />";
                    sApprovalRecord += "<condition attribute='regardingobjectid' operator='eq' value='" + gRegardingGuid + "'/>";
                    sApprovalRecord += "</filter>";
                    sApprovalRecord += "</entity>";
                    sApprovalRecord += "</fetch>";

                    #endregion

                    EntityCollection retrievedValue = service.RetrieveMultiple(new FetchExpression(sApprovalRecord));
                    iRetrieveValueCount = retrievedValue.Entities.Count;
                    if (iRetrieveValueCount > 0)
                    {
                        
                    }                    
                }

                catch (FaultException<OrganizationServiceFault> ex)
                {
                    throw new InvalidPluginExecutionException
                        ("An error occured in the follow up Plugin plug-in : " + ex);
                }

                catch (Exception ex)
                {
                    tracingService.Trace("FollowupPlugin: {0}", ex.ToString());
                    throw;
                }
            }
        }
`

Please assist how can I resolve this issue?

**Comment by siddharthgupta255** [comment] 2018-04-18 18:05
Error occurs at line
`EntityCollection retrievedValue = service.RetrieveMultiple(new FetchExpression(sApprovalRecord));`

**Comment by rbnswartz** [comment] 2018-04-18 18:32
@siddharthgupta255 I ran into the same thing because I mostly use late bound entities like you are. You should be able to get it to work by loading an assembly that contains your entity definitions into context.ProxyTypesAssembly. However if you are in a position like I am where it isn't an option to use early bound entities you can get around it by using a QueryExpression instead of a FetchExpression.

**Comment by jordimontana82** [comment] 2018-04-18 21:55
Hi guys,

Yep, this is by design, as when trying to parse strings with numeric values you need to generate an earlybound assembly (using crmsvcutil) so type checking works as expected.

Reuben is correct in that with a query expression you could pass numeric values directly, but a fetchxml expression is a bunch of plain text and we would run into all sorts of comparison exceptions (i.e. parsing "12.3" as a DateTime on side and one might except a string directly, or even a decimal number).

**Comment by jordimontana82** [comment] 2018-04-18 21:57
Closing this one as the solution is either

1) Generate an early bound assembly, and run the fetchxml query against it (if possible and recommended)
2) Use QueryExpression

**Closed by jordimontana82** 2018-04-18 21:57 UTC

**Comment by siddharthgupta255** [comment] 2018-04-19 05:13
@jordimontana82 & @rbnswartz   Thanks guys for your inputs. Really appreciate it :)
Advised my team to use QueryExpression instead of FetchExpression as we are avoiding using early bound entities.

**Comment by jordimontana82** [comment] 2018-04-19 13:56
@siddharthgupta255 I'm considering it would be good to retrieve types from the injected metadata (if any), in case ProxyTypesAssembly is null.

So you could specify which data types are relevant for your tests without using early bound. But again, I personally encourage early bound (compile time checks etc and other benefits) and only use late bound if there is no other option.
