### ISSUE TITLE
Multithread Retrieve

### ISSUE THREAD

**Issue by HeartOfDarkness96** [jordimontana82/fake-xrm-easy#465] opened 2019-12-11 07:45 UTC
In my tool I retrieve data from CRM in more threads  for better performance (_with: `var loadAccountModelCrm = new Task(delegate ...);`_)

I have an Unit-Test for this tool with Fake-XRM.
Sometimes I get an error that an element from the Fake-Entity can't find - but it definitly exists.
I think this error is caused by the Multi-Threading.

Version: 1.55.0
.Net: 4.7.2

**Comment by BetimBeja** [comment] 2019-12-11 07:49
Hello @HeartOfDarkness96 ,
please check issue #74 
Best regards,
Betim.

**Comment by mtone** [comment] 2020-01-05 05:50
I wrapped IOrganizationService with a lock in my unit tests. All my tests work on a fixture providing a property OrgService = new ThreadSafeOrganizationService(FakedContext.GetOrganizationService());

https://gist.github.com/mtone/5db05dd00fdf073df25ba60d444a706f

**Comment by jordimontana82** [comment] 2020-04-05 20:14
Closing as duplicate of #74

**Closed by jordimontana82** 2020-04-05 20:14 UTC
