### ISSUE TITLE
'entity_name' entity doesn't contain attribute with Name = 'attribute_name'. exception missing

### ISSUE THREAD

**Issue by ilyasgu** [jordimontana82/fake-xrm-easy#463] opened 2019-11-25 07:08 UTC
When adding a value to a non-existing attribute of an entity CRM run-time throws entity doesn't contain attribute exception. This is missing. Fake Xrm easy updated the entity and adds the attribute to the entity even the context.ProxyTypesAssembly is given. 

How can we achieve this issue?

I use "FakeXrmEasy.365" version="1.55.0" targetFramework="net452"

**Comment by jordimontana82** [comment] 2020-04-05 21:35
This is likely because the .dll in the ProxyTypesAssembly wasn't generated/updated with the latest attribute. I'm closing this one but if you still have this issue we would need a sample unit test to reproduce.

**Closed by jordimontana82** 2020-04-05 21:35 UTC
