### ISSUE TITLE
How to test OrganizationSericeProxy?

### ISSUE THREAD

**Issue by donamk** [jordimontana82/fake-xrm-easy#174] opened 2017-04-28 03:41 UTC
I am developing a crm client using early bound with WPF.

Like as this link https://msdn.microsoft.com/en-us/library/gg334754.aspx, I created a CrmServiceRepository and then using Autofac DI inject OrganizationServiceProxy.

```
public class CrmServiceRepository
{
    private readonly OrganizationServiceProxy _serviceProxy;

    public CrmServiceRepository(IOrganizationService service)
    {
        _serviceProxy = (OrganizationServiceProxy)service;
        _serviceProxy.EnableProxyTypes();
    }

    public void CreateAccount(Account account)
    {
        _serviceProxy.Create(account);
    }
}
```
for easy test, seem like required a fake OrganizationServiceProxy.
if  not, how can i test this kind of code?

Regards,

**Comment by jordimontana82** [comment] 2017-04-28 08:38
Thanks Donam.

This is a duplicate of #140  

OrganizationServiceProxy already implements IOrganizationService so rather storing the reference as a service proxy, you should store it as the interface directly, and then do _service.Create(account). 

By doing it that way you can inject a fake org service or a OrganizationServiceProxy using Autofac or similar.

Does that make sense?

**Comment by donamk** [comment] 2017-04-28 11:19
Hi Jordy,  Thank you for fast response.
Yes I saw #140 but I still don't understand what is the right way to implement this.

Change OrganizationServiceProxy to IOrganizationService is totally fine.
Then How should I handle `_serviceProxy.EnableProxyTypes()`?

The only way I can think is. in the constructor, check of the type of construct argment and then if tye type matchs with OrganizationServiceProxy, then call `EnableProxyTypes()` method.
```
public class CrmServiceRepository
{
    private readonly IOrganizationService _service;

    public CrmServiceRepository(IOrganizationService service)
    {
        _service = service;
        // type checch of service and then call EnableProxyTypes()
    }

    public void CreateAccount(Account account)
    {
        _service.Create(account);
    }
}
```
However, I don't like this approach, becuase the type checking code is not necessary for actualy produciton logic. How can I more elagantly hanlde this?

**Comment by jordimontana82** [comment] 2017-04-28 11:56
Ideally, your code should talk to an IOrganizationService directly and you could call EnableProxyTypes inside your DI container.

So your CrmServiceRepository instance would receive an actual OrganizationServiceProxy which had the proxy types already enabled.

But your only dependency inside CrmServiceRepository is IOrganizationService, nothing else.

**Closed** 2017-04-28 13:14 UTC
Labels: question
