### ISSUE TITLE
Dynamic CRM Code Activity mock CalculateRolleUpFieldRequest. Request for help

### ISSUE THREAD

**Issue by amwayDarshana** [jordimontana82/fake-xrm-easy#387] opened 2019-01-28 15:21 UTC
I sow your exception comment to develop this feature .

Any idea how to do this.
 This functionality is not available yet. Please consider contributing to the following Git project https://github.com/jordimontana82/fake-xrm-easy

![image](https://user-images.githubusercontent.com/42367701/51845832-447fe180-2353-11e9-9298-1f836bdb4589.png)

**Comment by BetimBeja** [comment] 2019-01-30 09:01
Hello @amwayDarshana ,
please check this [workaround](https://github.com/jordimontana82/fake-xrm-easy/issues/56#issuecomment-285880614).

Duplicate of  #56 
Best regards,
Betim.

**Comment by jordimontana82** [comment] 2019-02-05 09:03
HI @amwayDarshana , there is no CalculateRollupFieldRequest implemented in the framework yet (it would be actually a non trivial task, please see #56).

For most implementations, you can implement your fake message using the link @BetimBeja  provided, I'd say there's no even need to return any calculated result, only that your code actually calls that message for one specific field might be another option too.

Hope this helps, closing this issue now

**Closed** 2019-02-05 09:03 UTC
Labels: question

**Comment by darshana2000** [comment] 2019-02-07 02:42
@jordimontana82:  Thank you for your response. Appreciate your community help.
